[tools]
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
jq = "latest"
node = "latest"
python = "latest"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
trivy = "latest"
usage = "latest"
xh = "latest"
zoxide = "latest"
