[tools]
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
"go:github.com/walles/moor/v2/cmd/moor" = "latest"
jq = "latest"
node = "latest"
"npm:sql-formatter" = "latest"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
trivy = "latest"
usage = "latest"
vim = "latest"
xh = "latest"
zoxide = "latest"
